// nulish => ?? 

// console.log(NaN ?? 'salom');
// console.log(undefined ?? 'salom');
// console.log(null ?? 'salom');


// for loop

// const text='salom'
// let newText=''
// console.log(`${text} sozidagi belgilar soni ${text.length}`);

// for(let i=text.length-1; i>=0; i--){
//     console.log(text[i]);
// }

// for(let i=text.length-1; i>=0; i--){
//     newText+=(text[i]);
// }
// console.log(newText);


// while loop

 //task

//  const str1='men o"zbekistonni sevaman'
//  const str2='men'
//  let newStr1,newStr2
    
//     for (let i = 0; i < str1.length; i++) {
//          str1=[str2];
//         for (let n = 0; n < str2.length; n++) {
//           newStr2 = str2[n];
//         }
//     }
//     console.log();


// let str='1234444 5678 5444444432'
// let noNum=""
//     for (let i = 0; i < str.length; i++) {

//         if ((str[i-1]!=4)&&(str[i]==4)&&(str[i+1]!=4)) {
//             continue
//         }else{  
//             noNum += str[i]
//         }
//     }
//     console.log(noNum) 




// const str1='men o"zbekistonni sevaman'
// const str2='men'
// let newStr1,newStr2
   
//    for (let i = 0; i < str1.length; i++) {
//         str1=[str2];
//        for (let n = 0; n < str2.length; n++) {
//          newStr2 = str2[n];
//        }
//    }
//    console.log();


// let a='integr'
// let a2='maxmum'
// let n={"1" "2"}
// console.Log()





